name: Validaci贸n de Compilaci贸n (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compilar Proyecto
    runs-on: windows-latest

    steps:
    - name: Obtener c贸digo
      uses: actions/checkout@v4

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Configurar NuGet
      uses: NuGet/setup-nuget@v1.2

    - name: Restaurar dependencias
      run: nuget restore X-Wings_Orders.sln

    - name: Compilar Soluci贸n
      run: msbuild X-Wings_Orders.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Install Crystal Reports Runtime
      run: |
        Invoke-WebRequest -Uri "https://downloads.businessobjects.com/akdlm/crnetruntime/cr30sp25_redist_x64.msi" -OutFile "cr_runtime.msi"
        Start-Process msiexec.exe -ArgumentList '/i', 'cr_runtime.msi', '/quiet', '/norestart' -Wait